### ISSUE TITLE
Files in symlinked directories unable to preview

### ISSUE THREAD

**Issue by mardukpill** [ok-nick/c2pa-preview#1]
Trying to view the content credentials for files in a directory symlinked to another drive fails.

![image](https://github.com/ok-nick/c2pa-preview/assets/21978767/be5dfb71-753f-411b-a462-55a183abd093)

If I select the image directly from real directory c2pa-preview has no issues.
![image](https://github.com/ok-nick/c2pa-preview/assets/21978767/44f40460-9add-4321-8d2c-cebfc2ed015f)

**Comment by ok-nick** [comment]
Issue with Tauri v1 resolving symlinks, should work on Windows, not on other platforms. Functionality fixed in Tauri v2.
